name: designcode
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - asset/badges/
    - asset/certificates/
    - asset/icons/
    - asset/illustrations/
    - asset/images/
    - asset/logos/
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: asset/fonts/SFProText-Regular.ttf
        - asset: asset/fonts/SFProText-Bold.ttf
          weight: 800